server:
  port: 9999
  base-path: /communication-integration-template
  error:
    include-message: always

spring:
  main:
    web-application-type: none
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/FREEPDB1 #oracle jdbc:oracle:thin:@localhost:1521:xe
#    url: jdbc:oracle:thin:@localhost:1521:xe
    username: ENG
    password: evam123
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 45000
      validation-timeout: 7500
      idle-timeout: 1200000
      max-lifetime: 2700000
      data-source-properties:
        implicitCachingEnabled: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect #oracle org.hibernate.dialect.Oracle10gDialect
#        dialect: oracle.jdbc.driver.OracleDriver
#        dialect: org.hibernate.dialect.Oracle10gDialect
        dialect: org.hibernate.dialect.OracleDialect
        generate_statistics: true
        order_inserts: true
        order_updates: true
        use_sql_comments: false
        show_sql: false
        jdbc:
          batch_size: 100

logging:
  config: config/log4j2.xml

kafka:
  bootstrap-address: localhost:9092
  communication-uuid-check: true #If changed to false, the communicationUUID index should be removed. If it is not removed, it may be saved in the push status table incompletely.
  event-topic:
    name: campaignEventsTopic
    partition: 8
    replication: 1
    retention-ms: 43200000
  integration-topic:
    name: customcomTopic
    group: ooredooTopicCommunicationGroup01
    auto-offset-reset: earliest
    enable-auto-commit: false
    partition: 8
    replication: 1
    retention-ms: 43200000
    concurrency: 8
    max-pool-records: 1000
    #custom-config-properties:
    #  - key: "heartbeat.interval.ms"
    #    value: "3000"
  producer:
    buffer-memory: 33554432
    batch-size: 16384
    linger-ms: 300
    acks: 1
    #custom-config-properties:
    #  - key: "compression.type"
    #    value: "none"

### RATE LIMITER
#### The client send method is called a maximum of 5 times in 1 second.

#resilience4j.ratelimiter:
#  instances:
#    client-limiter:
#      limitForPeriod: 5
#      limitRefreshPeriod: 1s

cloud-marketing-survey-link-client:
  enabled: true
  endpoint-url: http://localhost:8105/survey-link/v1/multi
  link-url-prefix: https://d.evam.im/   #test : https://t.evam.im/
  headers:
    "Content-Type": "application/json"
    "Origin": "evam.com"
    "Authorization": "Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzdXJ2ZXktbWFuYWdlciIsImRvbWFpbnMiOlsiZXZhbS5jb20iXSwicGFja2FnZU5hbWVzIjpbImNvbS5ldmFtLmNsb3VkIl0sImlhdCI6MTY2ODQxNjc4NH0.OWxvNI22FrEtJsqDCceFk812EImKcq_b-zob7r0SRsg"
  link-pattern: "(SUR_[\\S]{5})"
  max-retry-attempts: 5
  initial-interval-milis: 1000
  interval-multiplier: 1.5


performance-counter:
  initial-delay: 30 #delay after first log
  period: 30 #time interval between loging
  time-unit: SECONDS #time unit for initial-delay and period ex: SECONDS,NANOSECONDS,MILLISECONDS,HOURS,MINUTES,DAYS
  scan-package: com.evam
  count-enabled: true
  scheduler-enabled: false
persister:
  persist-job-buffer-size: 500
  persist-pool-size: 1
  test-actors: 923345054724,923345054725,923345054726,923345054727,923345054728
  time-stamp-format-oracle: yyyy-MM-dd
  time-stamp-format-postgres: yyyy-MM-dd HH:mm:ss
  oracle-schema-name: PMP_EVAM
  postgresql-schema-name: evam
  insertSql:  "INSERT INTO OOREDOO_CUSTOM_SMS_REPORTING (ID, MSISDN, CONTRACT_ID, LANGUAGEPREFERENCE, MESSAGE_TEXT, SENDERID, TESTMODEENABLED, FLASHSMSENABLED, CAM_ID, CAMPAIGN_NAME, SEGMENT_NAME, TRANSACTION_ID, TREATMENT_NAME, TREATMENT_ID, OFFER_NAME, OFFER_ID, USECASE_TREATMENT_CODE, REF_TRANSACTION_ID, TREATMENT_CODE, TEMPLATE_NAME, MESSAGE_TYPE, CUSTOMER_TYPE, MESSAGE_ID, EVENT_NAME, MAPPING_NAME, PRICE, OFFER_CATEGORY, TG_CG_FLAG, DIRECTION, BUSINESS_GROUP, BUSINESS_SUBGROUP, CAMPAIGN_OBJECTIVE, CAMPAIGN_TYPE, OFFER_TYPE, OFFER_START_DATE, OFFER_END_DATE, ALT_CONTACT_NUMBER, MAIN_CAMPAIGN_NAME, DELIVERY_STATUS, STATUS, REASON, REASON_DETAIL) VALUES (OOREDOO_CUSTOM_SMS_SEQ.NEXTVAL, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)"
smpp:
  host: localhost
  port: 6693
  username: EVAM
  password: EVAM
  type: SMPP
  timeout: 10000
eec:
  ignite-client-file-path: config/ignite-client.json
  app-token: eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJFVkFNLVNFUlZJQ0UtTEFZRVIiLCJpYXQiOjE3NTk1Njk3OTEsInRva2VuVHlwZSI6IkFQUExJQ0FUSU9OIiwidG9rZW5DbGFpbXMiOnsidXNlcklkIjoxLCJ1c2VyQWxpYXMiOiJDb21tIiwicHJpdmlsZWdlcyI6W119fQ.pdCxFkMBXUFWWgh72rcHOgb9eIUiru0Sy4x8KyM9Npk
  pool-cache-name: OOREDOO_CUSTOM_CONTACT_POLICY
  trx-daily-cache: OOREDOO_CUSTOM_CP_TRANSACTION_DAILY
  trx-hist-cache: OOREDOO_CUSTOM_CP_TRANSACTION_HIST
  customer-detail-cache: CUSTOM_COMMUNICATION_DETAILS
  scenario-meta-params-cache: SCENARIO_META_PARAMETERS
  actor-segment-cache-name: ACTOR_SEGMENT_CP